# Generated by Django 5.2.4 on 2025-10-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_project_created_at_remove_project_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='highlight',
            field=models.TextField(blank=True),
        ),
    ]
