# Generated by Django 5.2.4 on 2026-04-11 00:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_blogpost_highlight"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
