# Generated by Django 5.2.1 on 2025-05-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.AddField(
            model_name="project",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
